name: apply4study
description: A sample learning app (local-only) with login, course detail, video player, progress tracking, AI tutor mock and dark mode toggle.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.18.0
  path_provider: ^2.0.0
  http: ^1.0.0
  workmanager: ^0.9.0+3
  go_router: ^17.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  table_calendar: ^3.0.9
  shared_preferences: ^2.1.1
  video_player: ^2.5.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.1.1
  confetti: ^0.8.0
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  flutter_local_notifications_linux: ^6.0.0
  path: ^1.9.1
  flutter_lints: ^6.0.0
  firebase_core: ^4.2.1
  connectivity_plus: ^7.0.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  ffi: ^2.1.4
  app_settings: ^6.1.1
  universal_html: ^2.2.4
  permission_handler: ^12.0.1
  country_code_picker: ^3.4.1
  flutter_native_splash: ^2.4.7
  timeago: ^3.7.1
  pull_to_refresh_flutter3: ^2.0.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  google_mlkit_text_recognition: ^0.15.0
  device_info_plus: ^12.2.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  fl_chart: ^1.1.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/banner1.svg
    - assets/images/banner2.svg
    - assets/images/avatar_male.svg
    - assets/images/avatar_female.svg
    - assets/videos/sample_video_placeholder.txt
    - assets/videos/mov_bbb.mp4
    - assets/images/logo.png
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/avatar_male.png
    - assets/images/avatar_female.png


flutter_native_splash:
  color: "#FF6A00"
  image: assets/images/logo.png
  android: true
  ios: true
  android_12:
    color: "#FF6A00"
    image: assets/images/logo.png
